### ISSUE TITLE
Get CI to green

### ISSUE THREAD

**Issue by diasdavid** [ipfs/interop#23]
See https://github.com/ipfs/interop/pull/21#issuecomment-392798261. Need to investigate more.

**Comment by alanshaw** [comment]
This is happening for me locally as well.

**Comment by diasdavid** [comment]
@alanshaw could it be related to the fact that go-ipfs doesn't really respect the sequential order?

**Comment by achingbrain** [comment]
Perhaps we should disable the PubSub tests until they can be improved?

**Comment by achingbrain** [comment]
I'm happy to dig in to this, but in the interim we should disable these tests and let other PRs be merged because they provide zero value, in fact negative value because they've stopped the go team from running the interop suite at all which harms the entire ecosystem: ipfs/go-ipfs#5053

They should be quarantined with a time limit.

More thoughts on this approach:

https://martinfowler.com/articles/nonDeterminism.html
https://blog.arkency.com/weekly-quarantine/

**Comment by diasdavid** [comment]
> we should disable these tests and let other PRs be merged because they provide zero value,

@achingbrain I agree, go for it 👍 

And thank you for providing useful reading links :)

**Comment by diasdavid** [comment]
Right now the issue is really the CI is super unstable (rans out of space). Tests run 100% otherwise

**Comment by alanshaw** [comment]
Yep, the pubsub issue (as mentioned in the original comment) was fixed in https://github.com/libp2p/js-libp2p-floodsub/pull/59 - this can be closed.
